### ISSUE TITLE
Include 'dirty tree' notation in generated version number

### ISSUE THREAD

**Issue by Slugger** [nemerosa/versioning#15]
The version info should include a notation if the build was done in a 'dirty tree' (unstaged or uncommitted changes).  `mylib-bug987-abc123.jar` isn't really a build from commit hash `abc123` if the developer made some local changes before building the jar and sending it to you.

In such a case, the version should be generated as something like `bug987-abc123-dirty` or whatever.  This way the developer either commits her changes to the fix branch and rebuilds so she can get back to this level when QA sends her a stacktrace when the fix doesn't work or she at least knows that any stacktrace she gets back isn't likely to be valid if she's continued working in that fix branch since doing that build.

A giant warning should be printed or maybe even fail the build altogether if a build is done in a dirty tree on a `release/*` branch.

**Comment by dcoraboeuf** [comment]
That's a good idea. The idea would be to detect is the working copy we use is dirty, with `git status`. I'll have a look.

**Comment by Slugger** [comment]
http://stackoverflow.com/questions/3878624/how-do-i-programmatically-determine-if-there-are-uncommited-changes/3879077#3879077

Here's a groovy port of the shell script from that SO page that I've used in the past to determine if a tree is dirty:

```
boolean isGitTreeDirty() {
	return 'git update-index -q --ignore-submodules --refresh'.execute().waitFor() ||
		'git diff-files --quiet --ignore-submodules --'.execute().waitFor() ||
		'git diff-index --cached --quiet HEAD --ignore-submodules --'.execute().waitFor()
}
```

**Comment by dcoraboeuf** [comment]
In order to detect the dirty state of the working copy, can't we just use the output of `git status` only? It should indicate either a non committed change in the index or in the working copy.

**Comment by dcoraboeuf** [comment]
I made the following test.

I add a new file `touch test.txt`. None of the commands above indicate a change.

I add this file to the index `git add test.txt`. None of the commands above indicate a change.

In both cases, `git status` will report that some changes are uncommitted.

**Comment by dcoraboeuf** [comment]
Calling `git status --porcelain` will not report anything is the working copy is OK.

**Comment by Slugger** [comment]
You can parse the output of `git status`, but the commands I provided simply return status codes denoting the state of the working copy.  Acting on status codes is much easier (and easier to maintain) than parsing output, especially when the output may not be consistent across versions of git.

***Clean Tree***
```
$ git diff-files --quiet --ignore-submodules --
$ echo $?
0
$ git diff-index --cached --quiet HEAD --ignore-submodules --
$ echo $?
0
```

***Unstaged Changes***
```
$ git diff-files --quiet --ignore-submodules --
$ echo $?
1
$ git diff-index --cached --quiet HEAD --ignore-submodules --
$ echo $?
0
```

***Uncommitted Changes***
```
$ git diff-files --quiet --ignore-submodules --
$ echo $?
0
$ git diff-index --cached --quiet HEAD --ignore-submodules --
$ echo $?
1
```

And so you can determine if the tree is dirty by checking if either of those commands returns non-zero, which is what `waitFor()` does in groovy.  The first command I included above is just to force the refresh of the index before checking it.

So you can parse `status` if you want, I just think using return codes is more reliable (and less likely to break unexpectedly in the future).

**Comment by dcoraboeuf** [comment]
Thanks for the feedback.

I've committed some changes in `feature/15-dirty` branch, for Git only first. Support for Subversion is coming (well, I have to support Svn as well, sorry).

About the Git tree state detection, I tried with you code:

```groovy
static boolean isGitTreeDirty(File dir) {
   return 'git update-index -q --ignore-submodules --refresh'.execute([], dir).waitFor() ||
      'git diff-files --quiet --ignore-submodules --'.execute([], dir).waitFor() ||
      'git diff-index --cached --quiet HEAD --ignore-submodules --'.execute([], dir).waitFor()
    }
```

but it did not return the expected result (see the tests in `GitInfoServiceTest`).

For the moment, I'm using:

```groovy
static boolean isGitTreeDirty(File dir) {
        return run(dir, 'git', 'status', '--porcelain').trim() != ''
}
```

Any idea?

**Comment by dcoraboeuf** [comment]
Well, I think I'm done, but for the fact I'm using `git status` only. I'll wait for your feedback before I merge the branch into the master and release
