### ISSUE TITLE
Unit tests won't run on Windows

### ISSUE THREAD

**Issue by Slugger** [nemerosa/versioning#17]
I'm guessing you're a linux only kind of guy? :)

Anyway, the unit tests won't run on Windows because of your use of the `touch` command.  I've got both Windows and Linux systems here so I was fine, but others may have troubles.

Should replace calling `touch` with `java.io.File.setLastModified()`.

There might be other factors affecting Windows, but it's the first one I hit and `touch` was used all over the place so I didn't even bother trying to fix it and logged into my linux box. :)

**Comment by dcoraboeuf** [comment]
It's indeed a long time I _touched_ a Windows machine :)

**Comment by dcoraboeuf** [comment]
I'm not sure I will do anything about this issue. The tests rely on the local creation of Git and Subversion repositories, and such creation rely heavily on shell commands and processes manipulation. Especially, the support for `git` commands is not really good, and the `svnserve -d` command I use to have a test SVN server does not return on Windows :)

All in all, that would be quite some effort to make the tests run on Windows - I'd prefer make sure the plug-in does its job on Windows.
