### ISSUE TITLE
SVN unit tests won't compile on Windows

### ISSUE THREAD

**Issue by Slugger** [nemerosa/versioning#18]
Two of the test method names cause issues on Windows.  The tests contain a closure and when the class file is generated for that closure the name groovyc wants to use results in an illegal file name on Windows and the compilation fails.

```
C:\Users\Derek\git\versioning>gradle testClasses
:compileJava UP-TO-DATE
:compileGroovy UP-TO-DATE
:processResources UP-TO-DATE
:classes UP-TO-DATE
:compileTestJava UP-TO-DATE
:compileTestGroovy
startup failed:
C:\Users\Derek\git\versioning\build\classes\test\net\nemerosa\versioning\svn\SVN
VersionTest$_SVN:_release_branch:_no_previous_tag_closure15.class (The filename,
 directory name, or volume label syntax is incorrect)

C:\Users\Derek\git\versioning\build\classes\test\net\nemerosa\versioning\svn\SVN
VersionTest$_SVN:_release_branch:_with_previous_tag_closure16.class (The filenam
e, directory name, or volume label syntax is incorrect)

2 errors

:compileTestGroovy FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileTestGroovy'.
> Compilation failed; see the compiler error output for details.
```
I've tracked it down to the fact that using two colons in the method name triggers the failure.  This is probably a groovy bug more than anything, but a lot easier/quicker for you to remove the double colons and gain immediate Windows support instead of relying on a groovy fix.  Not totally required or anything, but allows windows only users to clone and use the project.

**Comment by Slugger** [comment]
Turns out all colons have to be removed from the method names in order to run properly on Windows.

**Comment by dcoraboeuf** [comment]
Yes, I've seen that. Just my habit of coding on MacOS and Linux. Using now my Windows VM to correct this.
