### ISSUE TITLE
Auto tag untagged release branch as snapshot

### ISSUE THREAD

**Issue by Slugger** [nemerosa/versioning#19]
If I do a versionDisplay in `release/1.0` and the branch has no tags then `display=1.0.0`, but this really isn't 1.0.0 *yet*.  I think this should display `1.0.0-SNAPSHOT` since this isn't 1.0.0 until it's tagged as such.  Builds done from this branch would produce outputs for tags not yet created; causing confusion when QA reports back issues from these builds.

If this branch does have a tag for `1.0.0` and you do a versionDisplay even if your `HEAD` is at the tag then versionDisplay gives you `1.0.1`.  If a dev does a build at the `HEAD=tag` they should get a version equal to the tag.  If changes have been committed since the `1.0.0` tag, but those changes haven't been tagged you should get `1.0.1-SNAPSHOT`, until it's tagged then you'd get `1.0.1`.  Again, avoiding creating builds for tags not yet created.

**Comment by dcoraboeuf** [comment]
The real version is the _full_ version, not the _display_ one. But I agree with your point.

To summarise, you would have:

* `display` version = <computer version>-SNAPSHOT when not on the last tag
* `display` version = tag when on the tag

**Comment by dcoraboeuf** [comment]
I think I'll make this feature optional. In my case, I tag only at the very last time, when the publication is actually done. For everything, I'm only working with the full version, and the display version is just something I use for the... display and the final tagging (Git tagging, but also Docker image tagging).

I'll try to work on this in the next days - but I'm quite busy with other matters so do not expect a quick feedback for now :( Any pull request is welcome though :)

**Comment by dcoraboeuf** [comment]
Code is ready for Git (I won't do it for Subversion, not now at least). Can you tell me if it looks OK? If yes, I'll release this asap.

**Comment by dcoraboeuf** [comment]
I have added the corresponding documentation in the main README.

**Comment by Slugger** [comment]
I'll take a look during the weekend at some point and will get back to you
by Monday morning at the latest.

**Comment by dcoraboeuf** [comment]
Take your time - I won't release before next week.

**Comment by Slugger** [comment]
Looks good to me; I only focused on the release branch features when `releaseMode='snapshot'`; I didn't test for any regressions, etc.  New feature works as expected.
