### ISSUE TITLE
No version info reported for non-root projects builds.

### ISSUE THREAD

**Issue by mjcramer** [nemerosa/versioning#20]
This plugin has some really nice features and is very well done, however, there is a show-stopper for me in that it only works in the context of the root project. When working with git, the plugin looks for a '.git' subdirectory which would exist in the root of project directory that is checked out. My build actually occurs a couple directory levels below. It seems a simple call to project.getRootProject() in the GitScmService would remedy this...

**Comment by dcoraboeuf** [comment]
It looks indeed simple enough to do. I'll have a look in a few days.

**Comment by mjcramer** [comment]
Awesome! Thank you so much!!! This really helps me.

**Comment by dcoraboeuf** [comment]
You're welcome. I'll release next week - waiting for some feedback on another issue.
