### ISSUE TITLE
Let me turn off unnecessary warning message

### ISSUE THREAD

**Issue by Khoulaiz** [nemerosa/versioning#26]
I have a build containing a bunch of microservices as gradle subbuilds and I currently get spammed during the configuration phase with when I have a dirty work copy:

`[versioning] WARNING - the working copy has unstaged or uncommitted changes.`

Please let me turn that off. All my developers get confused by that messages while they use the build during development (and have of course a dirty workspace). The plugin is producing a good "dirty" version number, so the message is totally unnecessary IMHO.

My config look like this: 
```
allprojects {
    apply plugin: 'net.nemerosa.versioning'
    version = versioning.info.full
}
```
I like the approach of the dirty version number. Just the warning is not necessary.

**Comment by dcoraboeuf** [comment]
Hi,

The warning message is indeed currently displayed at all time. Would you be OK with an additional parameter like:

```
versioning {
   noWarningOnDirty = true
}
```

I need to maintain the default behaviour (having a warning).

Damien

**Comment by Khoulaiz** [comment]
Yeah sure, totally ok for me.

**Comment by dcoraboeuf** [comment]
Version 1.6.2 is available with this new feature. It's available in Bintray right now (`jcenter()`) but this can take some time before it's replicated in the Gradle plugin portal.
