### ISSUE TITLE
Provide tag information

### ISSUE THREAD

**Issue by marcphilipp** [nemerosa/versioning#30]
Are there any plans to provide the name of the tag(s) of the current commit similar to `branch` and `branchId`?

**Comment by dcoraboeuf** [comment]
Hi,

This could be possible, since we base the computation of the release on the latest tag available. Would this latest tag information be OK?

Thanks,
Damien.

**Comment by dcoraboeuf** [comment]
See also #32

**Comment by dcoraboeuf** [comment]
Closing in favour of the more generic issue at #32.
