### ISSUE TITLE
Please provide tag info in VersionInfo and allow custom logic for releases 

### ISSUE THREAD

**Issue by Hubbitus** [nemerosa/versioning#32]
I'm want use tag in my build artifacts name. But besides it parsed in [GitInfoService](https://github.com/nemerosa/versioning/blob/master/src/main/groovy/net/nemerosa/versioning/git/GitInfoService.groovy#L51) class [net.nemerosa.versioning.VersionInfo](https://github.com/nemerosa/versioning/blob/master/src/main/groovy/net/nemerosa/versioning/VersionInfo.groovy) does not include it. So it does not returned for `gradle` in convenient `versioning.info`.

Additionally you have [branchParser](https://github.com/nemerosa/versioning/blob/master/src/main/groovy/net/nemerosa/versioning/VersioningExtension.groovy#L69) closure which I may try to override to provide logic, but I want do it also against tag names not branch names.
Could it be possible generalize it say accept `VersionInfo` and return also something more generic?

**Comment by dcoraboeuf** [comment]
@Hubbitus, I've committed some adaptations on a separate branch. Can you review the changes and tell me what you think?

As for the `branchParser`, I'm not sure to understand what you want to achieve. I presume you want to have a different branch type if there is tag or not. Is that correct?

Best regards,
Damien.

**Comment by dcoraboeuf** [comment]
The `tag` (and `dirty`) information is now present in version 2.3.0.

However, I didn't do anything about the `branchParser` in this release.

If you need to apply some custom logic to the way you compute the version, I'd suggest you do it directly into your Gradle file, by using the version present in the `versioning.info` object.

Best regards,
Damien.

**Comment by Hubbitus** [comment]
Hello, @dcoraboeuf .
Thank you very much for the work and sorry for the silence. I'm ready to test any branch. What intended for that?

**Comment by Hubbitus** [comment]
My suggestion about customization was to provide some DSL for configuration to configure in gradle script some release-parsing information for project not only based on branch, but provide full version object.

You describe it in https://github.com/nemerosa/versioning#customisation

But for example in case if I want extract release/snapshot information from `tag` name (let it be 'release/v1.0.1') and not from `branch` name provide overriding of
```
   branchParser = { String branch, String separator = '/' ->
```
is not sufficient.
Why it may not be more generic and accept full instance of class `VersionInfo` or `SCMInfo` for consideration in body?

**Comment by dcoraboeuf** [comment]
@Hubbitus,

Do you think you could make a pull request to propose the change?

Thanks,
Damien.

**Comment by Hubbitus** [comment]
Yes, I Could try.

**Comment by Hubbitus** [comment]
Should it be against `release/2.3` branch or `master`? As I see master does not include last changes. Is it intentionally?

**Comment by dcoraboeuf** [comment]
Fixed :) You can branch from the `master`.

**Comment by dcoraboeuf** [comment]
FYI - I'll be on leave until next Monday - so take your time :)

**Comment by Hubbitus** [comment]
Thank you

**Comment by Hubbitus** [comment]
Does it issue need to be reopened? Or I should fill new one?

**Comment by dcoraboeuf** [comment]
I'll use the PR to track your change. Thanks.
