### ISSUE TITLE
Branch name on the detached head

### ISSUE THREAD

**Issue by piotrdytkowski** [nemerosa/versioning#40]
I'm running the versioning plugin with gitlab runner, so it's in the detached head state. I would like to get the proper branch name instead of "HEAD". When I run versionDisplay I get the following output:
```
:versionDisplay
[version] scm        = git
[version] branch     = HEAD
[version] branchType = HEAD
[version] branchId   = HEAD
[version] commit     = 60658794ffe4d9358668dfe40bc4f1a0a97ca2b8
[version] full       = HEAD-6065879
[version] base       = 
[version] build      = 6065879
[version] display    = HEAD-6065879
[version] tag        = 
[version] dirty      = false
```
But I have access to the branch name, gitlab output for reference:
```
$ echo "CI_COMMIT_REF_NAME " $CI_COMMIT_REF_NAME
CI_COMMIT_REF_NAME  GBFE-66
```
So I would like to use it, I tried to do 
```
versioning {
    branchEnv = ['CI_COMMIT_REF_NAME']
}
```
but it didn't change the HEAD to a proper branch name. Am I missing something? Is there any other way to achieve this?

Environment:
nemerosa/versioning 2.6.0
GitLab Community Edition 9.1.4 fed799a

**Comment by dcoraboeuf** [comment]
Hi Piotr,

What you're doing seems correct to me, so I would need to investigate further. Unfortunately, I have limited access to Internet right now (and no laptop) so it'll have to wait until end of July :( Sorry about the delay.

Best regards,
Damien.

**Comment by piotrdytkowski** [comment]
I found source of the problem. My configuration was in wrong order. `versioning` part has to be placed before referring to the version itself.
`
versioning {
    branchEnv = ['CI_COMMIT_REF_NAME']
}
version = versioning.info.display
`
This way it works, when you swap them and put `version = versioning.info.display` to the top then it doesn't resolve the config.

**Comment by dcoraboeuf** [comment]
Hi Piotr,

It does make sense indeed. The `versioning` must be indeed configured before you can use it.

BR
Damien
