### ISSUE TITLE
Improvement? : "Always snapshot" build

### ISSUE THREAD

**Issue by vlk32** [nemerosa/versioning#42]
Could I suggest improvement, please ?

I use Jenkins as a continous integration and now we're in progress of moving from mercurial+maven to git+gradle. I came across with two issues with snapshot builds.

1.  As I realised, snapshot feature works just on `release/X.Y`-branches. On another branches, this plugin never produce snapshot  build.
- **Issue :** If someone creates short lived feature-branch, then compiled artifact/library is without "-SNAPSHOT" suffix, so it's installed to "release" Maven-repository.
2. In case, that HEAD of branch is on the same changeset as a TAG, then then compiled artifact/library is named by this TAG and without "-SNAPSHOT"
- **Issue :** Second run of Jenkins build on the same changeset produce another artifact/library with the same name, and Maven central repository refuse uploading such artifact/library.

I would like to have simple configuration option which force this plugin to always generate "-SNAPSHOT" suffix. Configuration could be

    def releaseBuild = false // ... a build parameter from Jenkins ...
    versioning {
        releaseMode = releaseBuild ? 'snapshot' : 'always-snapshot'
    }

Another version of configuration could be :

    versioning {
        releaseBuild = false // ... a build parameter from Jenkins ...
        releaseMode = 'snapshot'
    }

**Comment by vlk32** [comment]
I've created pull request #43 for this improvement.

**Comment by dcoraboeuf** [comment]
Available in 2.6.1
