### ISSUE TITLE
No version information found

### ISSUE THREAD

**Issue by jschewebbn** [nemerosa/versioning#52]
I added the plugin to my build.gradle file and then executed `./gradlew versionDisplay` and got back "[version] No version can be computed from the SCM."

The root of my git repository does match the location of build.gradle, does that cause versioning problems?

**Comment by dcoraboeuf** [comment]
Hi,

I'm not sure to understand:

> The root of my git repository does match the location of build.gradle

Can you please give me a more precise description? See also the `gitRepoRootDir` option (on the README) for non standard Git structures.

Thanks,
Damien

**Comment by jschewebbn** [comment]
Root of my git repository is "/tmp/project", the build.gradle file is in "/tmp/project/test/code".
I added
```
versioning {
    gitRepoRootDir = '../..'
}
```
This results in
```
> Could not set unknown property 'gitRepoRootDir' for object of type net.nemerosa.versioning.VersioningExtension.
```

**Comment by dcoraboeuf** [comment]
Which version of the plugin do you use? Latest version is 2.7.1

**Comment by jschewebbn** [comment]
I took the instructions from the readme "    id 'net.nemerosa.versioning' version '2.0.0'"

**Comment by jschewebbn** [comment]
Changing it to 2.7.1 works.

**Comment by dcoraboeuf** [comment]
Good that it works.

I've updated the README.
