### ISSUE TITLE
Lightweight tags not considered by versioning.info.tag

### ISSUE THREAD

**Issue by chrillof** [nemerosa/versioning#64]
As the header suggests, there is an inconsistency in what is returned by the `versioning.info.tag` property while using Git.

If I greate a commit and creates a lightweight tag, say "v0.0.1", then I get different outputs from the `versioning.info.tag` and `versioning.info.lastTag`. In this scenario, `versioning.info.tag`  will return `null` indicating there is no tag, whereas `versioning.info.lastTag` will return "v0.0.1", as expected.

If I on the other hand creates an annotated tag, "v0.0.2", the result from both `versioning.info.tag` and `versioning.info.lastTag` will yield the same result, namely "v0.0.2", as expected.

To me, this seems like unwanted behaviour, but I've been wrong before. Thanks for a good plugin!

**Comment by reinhapa** [comment]
the lightweight tags worked up and including version 2.7.1 of versioning and stopped working after the next release...

**Comment by dcoraboeuf** [comment]
Available in 2.11.0
