### ISSUE TITLE
Use Lazy Configuration, Lazy Task Creation, Incremental Build

### ISSUE THREAD

**Issue by sdavids** [nemerosa/versioning#66]
You might want to adopt modern Gradle plugin conventions:

https://docs.gradle.org/current/userguide/lazy_configuration.html
https://docs.gradle.org/current/userguide/task_configuration_avoidance.html

https://docs.gradle.org/current/userguide/custom_tasks.html#incremental_tasks
https://docs.gradle.org/current/userguide/lazy_configuration.html#sec:working_with_task_dependencies_in_lazy_properties
https://docs.gradle.org/current/userguide/lazy_configuration.html#sec:unmodifiable_property
https://docs.gradle.org/current/userguide/more_about_tasks.html#sec:up_to_date_checks

Try `./gradlew help --scan`, under 'Performance' -> 'Configuration' you see the tasks created during configuration.

**Comment by dcoraboeuf** [comment]
Available in 2.14.0
