### ISSUE TITLE
Support for commit time

### ISSUE THREAD

**Issue by Darkvater** [nemerosa/versioning#80]
It would be great if this plugin could provide the commit date in the versioning.info object. Ideally the actual date the commit was pushed to the repo and not the original commit date which makes things very confusing in case there is rebase going on. 
The reason for this request is that com.gorylenko.gradle-git-properties and net.nemerosa does not work together nicely (they are using conflicting versions of grgit). Since this plugin is more flexible I would like to use it to generate the git.properties file for spring-boot versioning info amongst others.

**Comment by dcoraboeuf** [comment]
Available in 3.1.0
