### ISSUE TITLE
Unable to use 3.0.0 with JDK 8

### ISSUE THREAD

**Issue by szpak** [nemerosa/versioning#94]
[Spock](https://github.com/spockframework/spock/) uses your plugin and recently (thanks to Dependabot), we [discovered](https://github.com/spockframework/spock/runs/6659588816?check_suite_focus=true#step:3:141) that 3.0.0 requires JDK 11 (and Spock is still compatible with JDK8+).

Looking at the commits it seems to be done accidentally in:
https://github.com/nemerosa/versioning/commit/5b7a509baacdc20783abe292b67304dac95597c1

If yes, you should set `sourceCompatibility = '8'` or use a modern counterpart:
https://docs.gradle.org/current/userguide/building_java_projects.html

**Comment by dcoraboeuf** [comment]
Hi, support for Jdk 11 is no accident. It's been done to support the latest version of some dependencies like JGit.

Hence the change of major version number to indicate the incompatible change.

If your code depends on Jdk 8, I suggest you keep to the 2.x version.

Best regards, Damien

**Comment by szpak** [comment]
Ok. In that case, you could document (e.g. in README or in the release notes) that fact to avoid confusion and reports like that.

**Comment by dcoraboeuf** [comment]
It's documented in change log accessible from the readme

**Comment by szpak** [comment]
Ok, I have found it.

Maybe you could also put a link to wiki on the release page:
![image](https://user-images.githubusercontent.com/148013/171993512-4be2f4d4-492a-4fdf-9fec-c7ee4bf40032.png)

**Comment by szpak** [comment]
Btw, you could set `sourceCompatibility` in your build.gradle.kts anyway to make it clear. Currently, once build with JDK 17, it would be the required JDK version (not 11). Of course, having it automatically released from CI mitigate the problem (unless you accidentally bump the build image version :-) ).
